name: Biennale-ticket-monitor

on:
  # every 5 minutes (the shortest legal interval) :contentReference[oaicite:0]{index=0}
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: # manual run button

jobs:
  monitor:
    runs-on: ubuntu-latest
    # avoid overlapping runs if one is still going
    concurrency: biennale-monitor

    steps:
      - uses: actions/checkout@v4

      # ----  use GitHub Cache to keep ./cache/ between runs  ----
      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: cache
          key: biennale-ticket-cache

      # Python 3.12 is fine; pip only needs 'requests'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install --no-cache-dir requests beautifulsoup4 python-dotenv

      - name: Debug - Show cache restore status and folder state
        run: |
          echo "=== Cache debug info ==="
          echo "Cache restore result: ${{ steps.cache-restore.outputs.cache-hit }}"
          echo "Cache restore key: ${{ steps.cache-restore.outputs.cache-matched-key }}"
          if [ -d "cache" ]; then
            echo "Cache folder exists:"
            ls -la cache/
            echo "File count: $(find cache -type f | wc -l)"
          else
            echo "Cache folder does not exist"
          fi
          echo "=========================="

      - name: Run watcher
        run: python run.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}

      # Save updated cache back to same key
      - name: Save cache
        if: always() # save even if script failed  
        uses: actions/cache/save@v4
        with:
          path: cache
          key: biennale-ticket-cache

      - name: Debug - Show final cache state
        if: always()
        run: |
          echo "=== Final cache state ==="
          if [ -d "cache" ]; then
            echo "Cache folder contents after run:"
            ls -la cache/
            echo "File count: $(find cache -type f | wc -l)"
            echo "Total cache size: $(du -sh cache/ | cut -f1)"
          else
            echo "Cache folder still does not exist"
          fi
          echo "========================="
